---
- include: debian.yml
  when: ansible_os_family == "Debian"
  tags:
   - install_seeddms

- include: redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
  - install_seeddms

- include: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- name: Download seddms (remote)
  tags: seddms
    get_url:
      dest: "{{ ansible_data_path }}/{{ geoserver_redis_filename }}"
      url: "{{ seddms_mirror }}/{{ seddms_version }}/{{ seddms_filename }}"
      owner: {{ ansible_user }}
      group=: users
      mode: 0644
      sha256sum: {{ seddms_sha256sum }}
