---
# Install seeddms and its dependencies.
- name: Install seeddms dependencies.
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server
    - postfix
    - curl
    - openssl
    - tzdata